/*
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cielo24;

import com.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.LoginBody;
import org.openapitools.client.model.LoginResponse;
import org.openapitools.client.model.VerifyKeyResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Disabled
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * Get Account Settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSettingsTest() throws ApiException {
        Integer v = null;
        Object response = api.getSettings(v);
        // TODO: test validations
    }

    /**
     * Login to the cielo24 API to obtain an API access token for use when calling other methods. Optional arguments may be passed either as HTTP headers or query string parameters. Required arguments must be passed as query string parameters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        Integer v = null;
        LoginBody loginBody = null;
        LoginResponse response = api.login(v, loginBody);
        // TODO: test validations
    }

    /**
     * Logout of the current session, invalidating the API token.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        Integer v = null;
        api.logout(v);
        // TODO: test validations
    }

    /**
     * Test Auth
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyKeyTest() throws ApiException {
        Integer v = null;
        VerifyKeyResponse response = api.verifyKey(v);
        // TODO: test validations
    }

}
