/*
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.JobOptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobInfoResponse
 */
public class JobInfoResponseTest {
    private final JobInfoResponse model = new JobInfoResponse();

    /**
     * Model tests for JobInfoResponse
     */
    @Test
    public void testJobInfoResponse() {
        // TODO: test JobInfoResponse
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'jobName'
     */
    @Test
    public void jobNameTest() {
        // TODO: test jobName
    }

    /**
     * Test the property 'mediaLengthSeconds'
     */
    @Test
    public void mediaLengthSecondsTest() {
        // TODO: test mediaLengthSeconds
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'fidelity'
     */
    @Test
    public void fidelityTest() {
        // TODO: test fidelity
    }

    /**
     * Test the property 'jobStatus'
     */
    @Test
    public void jobStatusTest() {
        // TODO: test jobStatus
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'returnTargets'
     */
    @Test
    public void returnTargetsTest() {
        // TODO: test returnTargets
    }

    /**
     * Test the property 'sourceLanguage'
     */
    @Test
    public void sourceLanguageTest() {
        // TODO: test sourceLanguage
    }

    /**
     * Test the property 'targetLanguage'
     */
    @Test
    public void targetLanguageTest() {
        // TODO: test targetLanguage
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'completedDate'
     */
    @Test
    public void completedDateTest() {
        // TODO: test completedDate
    }

    /**
     * Test the property 'returnDate'
     */
    @Test
    public void returnDateTest() {
        // TODO: test returnDate
    }

    /**
     * Test the property 'authorizationDate'
     */
    @Test
    public void authorizationDateTest() {
        // TODO: test authorizationDate
    }

    /**
     * Test the property 'jobDifficulty'
     */
    @Test
    public void jobDifficultyTest() {
        // TODO: test jobDifficulty
    }

}
