/*
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.IWPEnum;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobOptions
 */
public class JobOptionsTest {
    private final JobOptions model = new JobOptions();

    /**
     * Model tests for JobOptions
     */
    @Test
    public void testJobOptions() {
        // TODO: test JobOptions
    }

    /**
     * Test the property 'customerApprovalSteps'
     */
    @Test
    public void customerApprovalStepsTest() {
        // TODO: test customerApprovalSteps
    }

    /**
     * Test the property 'customerApprovalTool'
     */
    @Test
    public void customerApprovalToolTest() {
        // TODO: test customerApprovalTool
    }

    /**
     * Test the property 'customMetadata'
     */
    @Test
    public void customMetadataTest() {
        // TODO: test customMetadata
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'returnIwp'
     */
    @Test
    public void returnIwpTest() {
        // TODO: test returnIwp
    }

    /**
     * Test the property 'generateMediaIntelligenceIwp'
     */
    @Test
    public void generateMediaIntelligenceIwpTest() {
        // TODO: test generateMediaIntelligenceIwp
    }

    /**
     * Test the property 'speakerId'
     */
    @Test
    public void speakerIdTest() {
        // TODO: test speakerId
    }

    /**
     * Test the property 'audioDescription'
     */
    @Test
    public void audioDescriptionTest() {
        // TODO: test audioDescription
    }

    /**
     * Test the property 'onScreenText'
     */
    @Test
    public void onScreenTextTest() {
        // TODO: test onScreenText
    }

    /**
     * Test the property 'musicLyrics'
     */
    @Test
    public void musicLyricsTest() {
        // TODO: test musicLyrics
    }

    /**
     * Test the property 'customSpecialHandling'
     */
    @Test
    public void customSpecialHandlingTest() {
        // TODO: test customSpecialHandling
    }

}
