/*
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets IWPEnum
 */
@JsonAdapter(IWPEnum.Adapter.class)
public enum IWPEnum {
  
  PREMIUM("PREMIUM"),
  
  INTERIM_PROFESSIONAL("INTERIM_PROFESSIONAL"),
  
  PROFESSIONAL("PROFESSIONAL"),
  
  SPEAKER_ID("SPEAKER_ID"),
  
  FINAL("FINAL"),
  
  MECHANICAL("MECHANICAL"),
  
  CUSTOMER_APPROVED_RETURN("CUSTOMER_APPROVED_RETURN"),
  
  CUSTOMER_APPROVED_TRANSLATION("CUSTOMER_APPROVED_TRANSLATION");

  private String value;

  IWPEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IWPEnum fromValue(String value) {
    for (IWPEnum b : IWPEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<IWPEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final IWPEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IWPEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IWPEnum.fromValue(value);
    }
  }
}

