/*
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PerformTranslationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-09T10:34:09.175-03:00[America/Sao_Paulo]")
public class PerformTranslationResponse {
  public static final String SERIALIZED_NAME_TRANSLATION_JOB_IDS = "translation_job_ids";
  @SerializedName(SERIALIZED_NAME_TRANSLATION_JOB_IDS)
  private List<String> translationJobIds = null;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public PerformTranslationResponse() { 
  }

  public PerformTranslationResponse translationJobIds(List<String> translationJobIds) {
    
    this.translationJobIds = translationJobIds;
    return this;
  }

  public PerformTranslationResponse addTranslationJobIdsItem(String translationJobIdsItem) {
    if (this.translationJobIds == null) {
      this.translationJobIds = new ArrayList<>();
    }
    this.translationJobIds.add(translationJobIdsItem);
    return this;
  }

   /**
   * Get translationJobIds
   * @return translationJobIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"0fbd6015910e42dca25a863c4925d77c\"]", value = "")

  public List<String> getTranslationJobIds() {
    return translationJobIds;
  }


  public void setTranslationJobIds(List<String> translationJobIds) {
    this.translationJobIds = translationJobIds;
  }


  public PerformTranslationResponse message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Child Translation Created for de. Child Translation already exists for fr", value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformTranslationResponse performTranslationResponse = (PerformTranslationResponse) o;
    return Objects.equals(this.translationJobIds, performTranslationResponse.translationJobIds) &&
        Objects.equals(this.message, performTranslationResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(translationJobIds, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformTranslationResponse {\n");
    sb.append("    translationJobIds: ").append(toIndentedString(translationJobIds)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("translation_job_ids");
    openapiFields.add("message");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PerformTranslationResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PerformTranslationResponse.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PerformTranslationResponse is not found in the empty JSON string", PerformTranslationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PerformTranslationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PerformTranslationResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("translation_job_ids") != null && !jsonObj.get("translation_job_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `translation_job_ids` to be an array in the JSON string but got `%s`", jsonObj.get("translation_job_ids").toString()));
      }
      if (jsonObj.get("message") != null && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerformTranslationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerformTranslationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerformTranslationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerformTranslationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PerformTranslationResponse>() {
           @Override
           public void write(JsonWriter out, PerformTranslationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PerformTranslationResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PerformTranslationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PerformTranslationResponse
  * @throws IOException if the JSON string is invalid with respect to PerformTranslationResponse
  */
  public static PerformTranslationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerformTranslationResponse.class);
  }

 /**
  * Convert an instance of PerformTranslationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

